import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import Navbar from '@/components/navbar'
import InfoLayer from '@/components/infoLayer'
import Technologieslist from '@/components/technologiesList'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Personal Website</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>

      <main className={styles.main}>
        <InfoLayer />
        <div className={styles.technologiesLayer}>
          <h2>Skills</h2>
          <Technologieslist />
        </div>
      </main>
    </div>
  )
}
