import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import Navbar from '@/components/navbar'
import InfoLayer from '@/components/infoLayer'
import Technologieslist from '@/components/technologiesList'
import ProjectsList from '@/components/projectsList'

export default function Home() {
  // need to work for responsive design
  return (
    <div className={styles.container}>
      <Head>
        <title>My Personal Website</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.container__wrapper}>
        <div
          className={
            styles.container__wrapper__blur
          }
        ></div>
        <main className={styles.main}>
          <InfoLayer />
          <section
            className={styles.technologiesLayer}
          >
            <h2>Technologies</h2>
            <Technologieslist />
          </section>
          <ProjectsList />
        </main>
      </div>
    </div>
  )
}
